-- MySQL Script generated by MySQL Workbench
-- Sun Nov  3 19:40:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema casa_ACME
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `casa_ACME` ;

-- -----------------------------------------------------
-- Schema casa_ACME
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casa_ACME` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `casa_ACME` ;

-- -----------------------------------------------------
-- Table `casa_ACME`.`tipo_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_ACME`.`tipo_empleado` ;

CREATE TABLE IF NOT EXISTS `casa_ACME`.`tipo_empleado` (
  `cod_tipo_empleado` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_tipo_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_ACME`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_ACME`.`empleado` ;

CREATE TABLE IF NOT EXISTS `casa_ACME`.`empleado` (
  `cod_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_nac` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `cod_tipo_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  INDEX `fk_empleado_tipo_empleado1_idx` (`cod_tipo_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_tipo_empleado1`
    FOREIGN KEY (`cod_tipo_empleado`)
    REFERENCES `casa_ACME`.`tipo_empleado` (`cod_tipo_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_ACME`.`caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_ACME`.`caja` ;

CREATE TABLE IF NOT EXISTS `casa_ACME`.`caja` (
  `cod_caja` INT NOT NULL AUTO_INCREMENT,
  `empleado_cod_empleado` INT NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`cod_caja`),
  INDEX `fk_caja_empleado1_idx` (`empleado_cod_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_caja_empleado1`
    FOREIGN KEY (`empleado_cod_empleado`)
    REFERENCES `casa_ACME`.`empleado` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_ACME`.`moneda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_ACME`.`moneda` ;

CREATE TABLE IF NOT EXISTS `casa_ACME`.`moneda` (
  `cod_moneda` INT NOT NULL AUTO_INCREMENT,
  `nom_moneda` VARCHAR(45) NULL,
  `tipo_cambio` DECIMAL(10,2) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_moneda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_ACME`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_ACME`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `casa_ACME`.`transaccion` (
  `cod_transaccion` INT NOT NULL AUTO_INCREMENT,
  `cod_empleado` INT NOT NULL,
  `cod_caja` INT NOT NULL,
  `cod_moneda` INT NOT NULL,
  `monto_transferido` DECIMAL(15,2) NULL,
  `monto_recibido` DECIMAL(15,2) NULL,
  `fecha_transaccion` DATETIME NULL,
  PRIMARY KEY (`cod_transaccion`),
  INDEX `fk_transaccion_empleado1_idx` (`cod_empleado` ASC) VISIBLE,
  INDEX `fk_transaccion_caja1_idx` (`cod_caja` ASC) VISIBLE,
  INDEX `fk_transaccion_moneda1_idx` (`cod_moneda` ASC) VISIBLE,
  CONSTRAINT `fk_transaccion_empleado1`
    FOREIGN KEY (`cod_empleado`)
    REFERENCES `casa_ACME`.`empleado` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaccion_caja1`
    FOREIGN KEY (`cod_caja`)
    REFERENCES `casa_ACME`.`caja` (`cod_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaccion_moneda1`
    FOREIGN KEY (`cod_moneda`)
    REFERENCES `casa_ACME`.`moneda` (`cod_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_ACME`.`saldo_caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_ACME`.`saldo_caja` ;

CREATE TABLE IF NOT EXISTS `casa_ACME`.`saldo_caja` (
  `cod_caja` INT NOT NULL,
  `cod_moneda` INT NOT NULL,
  `disponibilidad` DECIMAL(20,2) NULL,
  PRIMARY KEY (`cod_caja`, `cod_moneda`),
  INDEX `fk_caja_has_moneda_moneda1_idx` (`cod_moneda` ASC) VISIBLE,
  INDEX `fk_caja_has_moneda_caja_idx` (`cod_caja` ASC) VISIBLE,
  CONSTRAINT `fk_caja_has_moneda_caja`
    FOREIGN KEY (`cod_caja`)
    REFERENCES `casa_ACME`.`caja` (`cod_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caja_has_moneda_moneda1`
    FOREIGN KEY (`cod_moneda`)
    REFERENCES `casa_ACME`.`moneda` (`cod_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
